code --install-extension amazonwebservices.aws-toolkit-vscode --force
code --install-extension GrapeCity.gc-excelviewer --force
code --install-extension hilleer.yaml-plus-json --force
code --install-extension joaompinto.vscode-graphviz --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode-remote.remote-ssh-edit --force
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension ms-vscode-remote.vscode-remote-extensionpack --force
code --install-extension RandomFractalsInc.vscode-data-preview --force
code --install-extension tomoki1207.pdf --force